### ISSUE TITLE
Expose additional signals in diffractometer Device objects

### ISSUE THREAD

**Issue by klauer** [NSLS-II/hklpy#3]
- [x] UB matrix
- [x] sample name
- [x] energy/wavelength

cc @cmazzoli

**Comment by klauer** [comment]
cc @stuwilkins

**Comment by stuwilkins** [comment]
Thanks @klauer I think we need:

- [ ]  UB Matrix

as a minimum as from this all the post analysis can be done. As UB is independent of energy/wavelength it is not needed. For proper provenance we should probably have:

- [ ]  Lattice parameters (or reciprocal space lattice parameters)
- [ ]  Orientation Reflections used to calculate UB and wavelength/energy of measurement

I would stay away from sample name unless it is something that hklpy needs and uses.

**Comment by stuwilkins** [comment]
Attn @cmazzoli do you agree?
